# 蒙古国禁毒情报数据源：七大官方体系 + 全国媒体/通讯社 + 搜索聚合
# 目标：海量覆盖与毒品相关的新闻、通知、通告、数据、执法动态

SOURCES = [
    # ========== 1. 国家级禁毒统筹委员会体系 ==========
    {
        "system_id": 1,
        "system_name": "国家级禁毒统筹委员会体系",
        "org_name": "全国禁毒协调委员会（警察总局门户）",
        "org_name_mn": "Мансууруулах бодисын эсрэг үндэсний зохицуулах хороо",
        "base_url": "https://www.police.gov.mn",
        "seed_paths": ["/", "/news", "/mn/news", "/en/news", "/info", "/press"],
        "keywords_extra": ["мансууруулах", "хар тамхи", "drug"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 1,
        "system_name": "国家级禁毒统筹委员会体系",
        "org_name": "乌兰巴托市政府公开资讯",
        "org_name_mn": "Улаанбаатар хот",
        "base_url": "https://ulaanbaatar.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["мансууруулах", "урьдчилан сэргийлэх"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 1,
        "system_name": "国家级禁毒统筹委员会体系",
        "org_name": "蒙古国政府门户",
        "org_name_mn": "Засгийн газрын мэдээ",
        "base_url": "https://www.gov.mn",
        "seed_paths": ["/", "/mn", "/mn/news", "/en/news"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 2. 刑事缉毒执法体系 ==========
    {
        "system_id": 2,
        "system_name": "刑事缉毒执法体系",
        "org_name": "国家警察总局",
        "org_name_mn": "Цагдаагийн ерөнхий газар",
        "base_url": "https://www.police.gov.mn",
        "seed_paths": ["/", "/news", "/mn/news", "/en/news", "/press"],
        "keywords_extra": ["цагдаа", "баривчилгаа", "мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 2,
        "system_name": "刑事缉毒执法体系",
        "org_name": "国家情报局 GIA",
        "org_name_mn": "Тагнуулын ерөнхий газар",
        "base_url": "https://gia.gov.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["тагнуул", "мансууруулах"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 2,
        "system_name": "刑事缉毒执法体系",
        "org_name": "总检察院",
        "org_name_mn": "Улсын ерөнхий прокурорын газар",
        "base_url": "https://www.prosecutor.mn",
        "seed_paths": ["/", "/news", "/info", "/press"],
        "keywords_extra": ["прокурор", "мансууруулах", "гэмт хэрэг"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 2,
        "system_name": "刑事缉毒执法体系",
        "org_name": "法院判决执行总局（监狱）",
        "org_name_mn": "Шүүхийн шийдвэр гүйцэтгэх ерөнхий газар",
        "base_url": "https://www.gs.gov.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["хорих", "мансууруулах", "донтсон"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 3. 麻精药品与制毒原料行业监管体系 ==========
    {
        "system_id": 3,
        "system_name": "麻精药品与制毒原料行业监管体系",
        "org_name": "卫生部",
        "org_name_mn": "Эрүүл мэндийн яам",
        "base_url": "https://www.mohs.mn",
        "seed_paths": ["/", "/news", "/info", "/announcement"],
        "keywords_extra": ["мансууруулах", "эм", "донтсон"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 3,
        "system_name": "麻精药品与制毒原料行业监管体系",
        "org_name": "卫生部（gov.mn 组织页）",
        "org_name_mn": "ЭМЯ",
        "base_url": "https://www.gov.mn",
        "seed_paths": ["/mn/organization/moh", "/en/organization/moh"],
        "keywords_extra": ["мансууруулах", "эрүүл мэнд"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 3,
        "system_name": "麻精药品与制毒原料行业监管体系",
        "org_name": "环境与旅游部",
        "org_name_mn": "Байгаль орчин, аялал жуулчлалын яам",
        "base_url": "https://www.met.gov.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["ургамал", "каннабис", "опиум"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 3,
        "system_name": "麻精药品与制毒原料行业监管体系",
        "org_name": "法律信息中心",
        "org_name_mn": "Legalinfo",
        "base_url": "https://www.legalinfo.mn",
        "seed_paths": ["/", "/law", "/mn"],
        "keywords_extra": ["мансууруулах", "хар тамхи", "narcotic"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 4. 边境海关缉毒查验体系 ==========
    {
        "system_id": 4,
        "system_name": "边境海关缉毒查验体系",
        "org_name": "海关总局",
        "org_name_mn": "Гаалийн ерөнхий газар",
        "base_url": "https://www.customs.gov.mn",
        "seed_paths": ["/", "/news", "/info", "/press"],
        "keywords_extra": ["гааль", "хил", "мансууруулах", "баривчилгаа"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 4,
        "system_name": "边境海关缉毒查验体系",
        "org_name": "边防局",
        "org_name_mn": "Хилийн цэргийн удирдах газар",
        "base_url": "https://bpo.gov.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["хил", "мансууруулах"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 4,
        "system_name": "边境海关缉毒查验体系",
        "org_name": "外交部（gov.mn）",
        "org_name_mn": "ГХЯ",
        "base_url": "https://www.gov.mn",
        "seed_paths": ["/mn/organization/mfa", "/en/organization/mfa"],
        "keywords_extra": ["мансууруулах", "хил", "хамтын ажиллагаа"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 4,
        "system_name": "边境海关缉毒查验体系",
        "org_name": "移民局",
        "org_name_mn": "Гадаадын иргэн, харьяатын газар",
        "base_url": "https://immigration.gov.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["хил", "мансууруулах", "trafficking"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 5. 全国地方层级禁毒机构 ==========
    {
        "system_id": 5,
        "system_name": "全国地方层级禁毒机构",
        "org_name": "警察总局地方动态",
        "org_name_mn": "Аймгийн цагдаа",
        "base_url": "https://www.police.gov.mn",
        "seed_paths": ["/", "/news", "/mn/news"],
        "keywords_extra": ["аймаг", "мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 5,
        "system_name": "全国地方层级禁毒机构",
        "org_name": "乌兰巴托九大区资讯",
        "org_name_mn": "УБ дүүрэг",
        "base_url": "https://ulaanbaatar.mn",
        "seed_paths": ["/", "/news"],
        "keywords_extra": ["дүүрэг", "мансууруулах"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 6. 戒毒康复医疗机构体系 ==========
    {
        "system_id": 6,
        "system_name": "戒毒康复医疗机构体系",
        "org_name": "卫生系统戒毒康复公开资讯",
        "org_name_mn": "Нөхөн сэргээх",
        "base_url": "https://www.mohs.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["донтсон", "нөхөн сэргээх", "мансууруулах", "эмчилгээ"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 6,
        "system_name": "戒毒康复医疗机构体系",
        "org_name": "卫生门户 moh.mn",
        "org_name_mn": "ЭМЯ мэдээ",
        "base_url": "https://www.moh.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["донтсон", "мансууруулах"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 7. 国际禁毒协作机构 ==========
    {
        "system_id": 7,
        "system_name": "国际禁毒协作机构",
        "org_name": "UNODC 东亚及太平洋",
        "org_name_mn": "UNODC",
        "base_url": "https://www.unodc.org",
        "seed_paths": [
            "/unodc/en/frontpage.html",
            "/easternasiaandpacific/index.html",
            "/unodc/en/drug-trafficking/index.html",
            "/unodc/en/press/index.html",
        ],
        "keywords_extra": ["Mongolia", "UNODC", "drug", "trafficking", "narcotic"],
        "lang": "en",
        "source_type": "official",
        "domain_allowlist": ["unodc.org", "www.unodc.org"],
    },
    {
        "system_id": 7,
        "system_name": "国际禁毒协作机构",
        "org_name": "蒙古国政府国际合作",
        "org_name_mn": "mongolia.gov.mn",
        "base_url": "https://mongolia.gov.mn",
        "seed_paths": ["/", "/news"],
        "keywords_extra": ["мансууруулах", "олон улсын", "drug"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 8. 全国媒体 / 通讯社 / 新闻门户（海量覆盖） ==========
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "蒙通社 MONTSAME",
        "org_name_mn": "МОНЦАМЭ",
        "base_url": "https://www.montsame.mn",
        "seed_paths": ["/", "/mn", "/en", "/ru"],
        "keywords_extra": ["мансууруулах", "хар тамхи", "drug", "narcotic"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "GoGo 新闻",
        "org_name_mn": "GoGo.mn",
        "base_url": "https://gogo.mn",
        "seed_paths": ["/", "/r/news", "/news"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "IKON 新闻",
        "org_name_mn": "ikon.mn",
        "base_url": "https://ikon.mn",
        "seed_paths": ["/", "/n"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "News.mn",
        "org_name_mn": "news.mn",
        "base_url": "https://news.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "UB Post",
        "org_name_mn": "The UB Post",
        "base_url": "https://www.ubpost.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["drug", "narcotic", "trafficking", "Mongolia"],
        "lang": "en",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "Bloombergtv Mongolia",
        "org_name_mn": "bloombergtv.mn",
        "base_url": "https://www.bloombergtv.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "Zarig 新闻",
        "org_name_mn": "zarig.mn",
        "base_url": "https://zarig.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "Olloo 新闻",
        "org_name_mn": "olloo.mn",
        "base_url": "https://www.olloo.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "Shuud 新闻",
        "org_name_mn": "shuud.mn",
        "base_url": "https://www.shuud.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "Undesnii Shuudan",
        "org_name_mn": "dnn.mn",
        "base_url": "https://dnn.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "media",
    },
]

# Google News / 关键词搜索聚合（保证海量命中）
SEARCH_FEEDS = [
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "谷歌新闻·蒙语禁毒",
        "query": "мансууруулах бодис",
        "hl": "mn",
        "gl": "mn",
        "ceid": "MN:mn",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "谷歌新闻·黑毒品",
        "query": "хар тамхи",
        "hl": "mn",
        "gl": "mn",
        "ceid": "MN:mn",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "谷歌新闻·缉毒查获",
        "query": "мансууруулах бодис баривчилгаа",
        "hl": "mn",
        "gl": "mn",
        "ceid": "MN:mn",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "谷歌新闻·警察禁毒",
        "query": "цагдаа мансууруулах",
        "hl": "mn",
        "gl": "mn",
        "ceid": "MN:mn",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "谷歌新闻·海关毒品",
        "query": "гааль мансууруулах",
        "hl": "mn",
        "gl": "mn",
        "ceid": "MN:mn",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "谷歌新闻·英语 Mongolia drug",
        "query": "Mongolia drug OR narcotic OR trafficking OR methamphetamine",
        "hl": "en",
        "gl": "us",
        "ceid": "US:en",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "谷歌新闻·英语 Mongolia heroin",
        "query": "Mongolia heroin OR cannabis OR cocaine OR fentanyl OR precursor",
        "hl": "en",
        "gl": "us",
        "ceid": "US:en",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "谷歌新闻·中文蒙古毒品",
        "query": "蒙古 毒品 OR 缉毒 OR 禁毒 OR 贩毒",
        "hl": "zh-CN",
        "gl": "cn",
        "ceid": "CN:zh-Hans",
    },
    {
        "system_id": 7,
        "system_name": "国际禁毒协作机构",
        "org_name": "谷歌新闻·UNODC Mongolia",
        "query": "UNODC Mongolia drug",
        "hl": "en",
        "gl": "us",
        "ceid": "US:en",
    },
    {
        "system_id": 4,
        "system_name": "边境海关缉毒查验体系",
        "org_name": "谷歌新闻·中蒙边境毒品",
        "query": "Mongolia China border drug OR narcotic seizure",
        "hl": "en",
        "gl": "us",
        "ceid": "US:en",
    },
]

# 禁毒相关关键词（扩大覆盖，蒙/英/俄/中）
DRUG_KEYWORDS = [
    # 中文
    "毒品", "禁毒", "缉毒", "麻精", "制毒", "戒毒", "成瘾", "贩毒", "走私毒品",
    "易制毒", "管制药品", "合成毒品", "冰毒", "海洛因", "大麻", "可卡因",
    "芬太尼", "跨境缉毒", "口岸查获", "专项行动", "毒情", "吸毒", "涉毒",
    "麻黄碱", "氯胺酮", "K粉", "摇头丸", "鸦片", "罂粟",
    # 蒙语（西里尔）——核心词尽量短，提高命中
    "мансууруулах", "хар тамхи", "тамхины", "донтсон", "донтлох",
    "урьдчилан сэргийлэх", "баривчилгаа", "хилээр",
    "синтетик", "опиум", "героин", "кокаин", "каннабис", "марихуан",
    "нөхөн сэргээх", "наркотик", "наркотикын", "прекурсор",
    "метамфетамин", "амфетамин", "экстази", "кетамин",
    # 英语
    "drug", "drugs", "narcotic", "narcotics", "trafficking", "trafficker",
    "seizure", "seized", "precursor", "controlled substance",
    "addiction", "addict", "rehabilitation", "opioid", "opium",
    "methamphetamine", "meth", "heroin", "cannabis", "marijuana",
    "cocaine", "fentanyl", "UNODC", "anti-drug", "antidrug",
    "interdiction", "smuggling", "psychotropic", "stimulant",
    # 俄语
    "наркотик", "наркотиков", "контрабанда", "изъятие", "прекурсор",
    "наркомания", "реабилитация", "героин", "кокаин", "каннабис",
]

CRITICAL_KEYWORDS = [
    "专项行动", "跨境缉毒", "新法", "口岸严查", "合成毒品", "易制毒",
    "缉毒大案", "管制品", "大规模查获", "seizure", "seized",
    "баривчилгаа", "тусгай ажиллагаа", "UNODC", "trafficking",
]

# 允许域名：官方 + 媒体 + 常见新闻聚合落地页
ALLOWED_DOMAINS = [
    # 官方
    "police.gov.mn", "www.police.gov.mn",
    "ulaanbaatar.mn", "www.ulaanbaatar.mn",
    "mohs.mn", "www.mohs.mn", "moh.mn", "www.moh.mn",
    "gia.gov.mn", "www.gia.gov.mn",
    "prosecutor.mn", "www.prosecutor.mn",
    "gs.gov.mn", "www.gs.gov.mn",
    "met.gov.mn", "www.met.gov.mn",
    "customs.gov.mn", "www.customs.gov.mn",
    "bpo.gov.mn", "www.bpo.gov.mn",
    "mfa.gov.mn", "www.mfa.gov.mn",
    "immigration.gov.mn", "www.immigration.gov.mn",
    "zasag.mn", "www.zasag.mn",
    "gov.mn", "www.gov.mn",
    "mongolia.gov.mn", "www.mongolia.gov.mn",
    "unodc.org", "www.unodc.org",
    "legalinfo.mn", "www.legalinfo.mn",
    # 媒体
    "montsame.mn", "www.montsame.mn",
    "gogo.mn", "www.gogo.mn",
    "ikon.mn", "www.ikon.mn",
    "news.mn", "www.news.mn",
    "ubpost.mn", "www.ubpost.mn",
    "bloombergtv.mn", "www.bloombergtv.mn",
    "zarig.mn", "www.zarig.mn",
    "olloo.mn", "www.olloo.mn",
    "shuud.mn", "www.shuud.mn",
    "dnn.mn", "www.dnn.mn",
    "itoim.mn", "www.itoim.mn",
    "medee.mn", "www.medee.mn",
    "unuudur.mn", "www.unuudur.mn",
    "baabar.mn", "www.baabar.mn",
    "news.google.com",
]

# 搜索结果落地页：允许更多 .mn 新闻域名（仍排除明显无关国际站）
ALLOW_ANY_MN_DOMAIN = True
