# 蒙古国禁毒情报数据源：七大官方体系 + 全国媒体
# 关键词与搜索任务见 config/drug_lexicon.py

from config.drug_lexicon import (
    ALERT_KEYWORDS,
    all_drug_keywords,
    build_search_queries,
)

SOURCES = [
    # ========== 1. 国家级禁毒统筹委员会体系 ==========
    {
        "system_id": 1,
        "system_name": "国家级禁毒统筹委员会体系",
        "org_name": "全国禁毒协调委员会（警察总局门户）",
        "org_name_mn": "Мансууруулах бодисын эсрэг үндэсний зохицуулах хороо",
        "base_url": "https://www.police.gov.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 1,
        "system_name": "国家级禁毒统筹委员会体系",
        "org_name": "乌兰巴托市政府",
        "org_name_mn": "Улаанбаатар хот",
        "base_url": "https://ulaanbaatar.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 1,
        "system_name": "国家级禁毒统筹委员会体系",
        "org_name": "蒙古国政府门户",
        "org_name_mn": "Засгийн газар",
        "base_url": "https://www.gov.mn",
        "seed_paths": ["/", "/mn"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 2. 刑事缉毒执法体系 ==========
    {
        "system_id": 2,
        "system_name": "刑事缉毒执法体系",
        "org_name": "国家警察总局",
        "org_name_mn": "Цагдаагийн ерөнхий газар",
        "base_url": "https://www.police.gov.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["цагдаа", "баривчилгаа", "мансууруулах"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 2,
        "system_name": "刑事缉毒执法体系",
        "org_name": "国家情报局 GIA",
        "org_name_mn": "Тагнуулын ерөнхий газар",
        "base_url": "https://gia.gov.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 2,
        "system_name": "刑事缉毒执法体系",
        "org_name": "总检察院",
        "org_name_mn": "Улсын ерөнхий прокурорын газар",
        "base_url": "https://www.prosecutor.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "гэмт хэрэг"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 2,
        "system_name": "刑事缉毒执法体系",
        "org_name": "法院判决执行总局",
        "org_name_mn": "ШШГЕГ",
        "base_url": "https://www.gs.gov.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "донтсон"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 3. 麻精药品与制毒原料 ==========
    {
        "system_id": 3,
        "system_name": "麻精药品与制毒原料行业监管体系",
        "org_name": "卫生部",
        "org_name_mn": "ЭМЯ",
        "base_url": "https://www.gov.mn",
        "seed_paths": ["/mn/organization/moh", "/en/organization/moh"],
        "keywords_extra": ["мансууруулах", "эм"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 3,
        "system_name": "麻精药品与制毒原料行业监管体系",
        "org_name": "法律信息中心",
        "org_name_mn": "Legalinfo",
        "base_url": "https://www.legalinfo.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 4. 边境海关 ==========
    {
        "system_id": 4,
        "system_name": "边境海关缉毒查验体系",
        "org_name": "海关总局",
        "org_name_mn": "Гаалийн ерөнхий газар",
        "base_url": "https://www.customs.gov.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["гааль", "мансууруулах", "баривчилгаа"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 4,
        "system_name": "边境海关缉毒查验体系",
        "org_name": "外交部（gov.mn）",
        "org_name_mn": "ГХЯ",
        "base_url": "https://www.gov.mn",
        "seed_paths": ["/mn/organization/mfa"],
        "keywords_extra": ["мансууруулах", "хил"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 4,
        "system_name": "边境海关缉毒查验体系",
        "org_name": "移民局",
        "org_name_mn": "Иргэний харьяалал",
        "base_url": "https://immigration.gov.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["хил", "мансууруулах"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 5. 地方 ==========
    {
        "system_id": 5,
        "system_name": "全国地方层级禁毒机构",
        "org_name": "警察总局地方动态",
        "org_name_mn": "Аймгийн цагдаа",
        "base_url": "https://www.police.gov.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "official",
    },
    {
        "system_id": 5,
        "system_name": "全国地方层级禁毒机构",
        "org_name": "乌兰巴托九区资讯",
        "org_name_mn": "УБ дүүрэг",
        "base_url": "https://ulaanbaatar.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 6. 戒毒康复 ==========
    {
        "system_id": 6,
        "system_name": "戒毒康复医疗机构体系",
        "org_name": "卫生系统戒毒康复资讯",
        "org_name_mn": "Нөхөн сэргээх",
        "base_url": "https://www.gov.mn",
        "seed_paths": ["/mn/organization/moh"],
        "keywords_extra": ["донтсон", "нөхөн сэргээх", "мансууруулах"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 7. 国际协作 ==========
    {
        "system_id": 7,
        "system_name": "国际禁毒协作机构",
        "org_name": "UNODC",
        "org_name_mn": "UNODC",
        "base_url": "https://www.unodc.org",
        "seed_paths": [
            "/unodc/en/frontpage.html",
            "/easternasiaandpacific/index.html",
            "/unodc/en/drug-trafficking/index.html",
        ],
        "keywords_extra": ["Mongolia", "drug", "narcotic", "trafficking"],
        "lang": "en",
        "source_type": "official",
    },
    {
        "system_id": 7,
        "system_name": "国际禁毒协作机构",
        "org_name": "蒙古国政府国际合作",
        "org_name_mn": "mongolia.gov.mn",
        "base_url": "https://mongolia.gov.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "drug"],
        "lang": "mn",
        "source_type": "official",
    },
    # ========== 8. 全国媒体 ==========
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "蒙通社 MONTSAME",
        "org_name_mn": "МОНЦАМЭ",
        "base_url": "https://www.montsame.mn",
        "seed_paths": ["/", "/mn", "/en"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "GoGo 新闻",
        "org_name_mn": "GoGo.mn",
        "base_url": "https://gogo.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "IKON 新闻",
        "org_name_mn": "ikon.mn",
        "base_url": "https://ikon.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "News.mn",
        "org_name_mn": "news.mn",
        "base_url": "https://news.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах", "хар тамхи"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "UB Post",
        "org_name_mn": "The UB Post",
        "base_url": "https://www.ubpost.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["drug", "narcotic", "Mongolia"],
        "lang": "en",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "Zarig 新闻",
        "org_name_mn": "zarig.mn",
        "base_url": "https://zarig.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "Olloo 新闻",
        "org_name_mn": "olloo.mn",
        "base_url": "https://www.olloo.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах"],
        "lang": "mn",
        "source_type": "media",
    },
    {
        "system_id": 8,
        "system_name": "全国媒体与公开资讯",
        "org_name": "Shuud 新闻",
        "org_name_mn": "shuud.mn",
        "base_url": "https://www.shuud.mn",
        "seed_paths": ["/"],
        "keywords_extra": ["мансууруулах"],
        "lang": "mn",
        "source_type": "media",
    },
]

# 由词库动态生成搜索任务（全量也强制近期 when）
SEARCH_FEEDS = build_search_queries(mode="full", when="1y")

DRUG_KEYWORDS = all_drug_keywords()
CRITICAL_KEYWORDS = ALERT_KEYWORDS

ALLOWED_DOMAINS = [
    "police.gov.mn", "www.police.gov.mn",
    "ulaanbaatar.mn", "www.ulaanbaatar.mn",
    "mohs.mn", "www.mohs.mn", "moh.mn", "www.moh.mn",
    "gia.gov.mn", "www.gia.gov.mn",
    "prosecutor.mn", "www.prosecutor.mn",
    "gs.gov.mn", "www.gs.gov.mn",
    "met.gov.mn", "www.met.gov.mn",
    "customs.gov.mn", "www.customs.gov.mn",
    "bpo.gov.mn", "www.bpo.gov.mn",
    "mfa.gov.mn", "www.mfa.gov.mn",
    "immigration.gov.mn", "www.immigration.gov.mn",
    "zasag.mn", "www.zasag.mn",
    "gov.mn", "www.gov.mn",
    "mongolia.gov.mn", "www.mongolia.gov.mn",
    "unodc.org", "www.unodc.org",
    "legalinfo.mn", "www.legalinfo.mn",
    "montsame.mn", "www.montsame.mn",
    "gogo.mn", "www.gogo.mn", "web.gogo.mn",
    "ikon.mn", "www.ikon.mn",
    "news.mn", "www.news.mn",
    "ubpost.mn", "www.ubpost.mn",
    "bloombergtv.mn", "www.bloombergtv.mn",
    "zarig.mn", "www.zarig.mn",
    "olloo.mn", "www.olloo.mn",
    "shuud.mn", "www.shuud.mn",
    "dnn.mn", "www.dnn.mn",
    "itoim.mn", "www.itoim.mn",
    "medee.mn", "www.medee.mn",
    "unuudur.mn", "www.unuudur.mn",
    "thediplomat.com", "www.thediplomat.com",
    "news.google.com",
    "1212.mn", "www.1212.mn",
    "mnb.mn", "www.mnb.mn", "news.mnb.mn",
    "ocindex.net", "www.ocindex.net",
    "parliament.mn", "www.parliament.mn",
]

# 合并全球媒体与国际机构域名
from config.global_media import GLOBAL_ALLOWED_DOMAINS  # noqa: E402
from config.forum_search import FORUM_ALLOWED_DOMAINS  # noqa: E402

ALLOWED_DOMAINS = list(
    dict.fromkeys(ALLOWED_DOMAINS + GLOBAL_ALLOWED_DOMAINS + FORUM_ALLOWED_DOMAINS)
)

ALLOW_ANY_MN_DOMAIN = True
# 搜索聚合入库时允许全球主流媒体域名（已在白名单）
ALLOW_GLOBAL_MEDIA = True
ALLOW_FORUM_DOMAINS = True
