# 蒙古国禁毒七大体系官方数据源清单（严格限定官方机构）
# 系统启动后会递归发现下级栏目并自动写入数据库，无需人工补充。
# 说明：部分机构官网可能改版/合并，爬虫会记录可达性并保留种子 URL。

SOURCES = [
    # ========== 1. 国家级禁毒统筹委员会体系 ==========
    {
        "system_id": 1,
        "system_name": "国家级禁毒统筹委员会体系",
        "org_name": "全国禁毒协调委员会",
        "org_name_mn": "Мансууруулах бодисын эсрэг үндэсний зохицуулах хороо",
        "base_url": "https://www.police.gov.mn",
        "seed_paths": ["/", "/news", "/info", "/prevention"],
        "keywords_extra": ["зохицуулах хороо", "мансууруулах", "coordination"],
        "lang": "mn",
    },
    {
        "system_id": 1,
        "system_name": "国家级禁毒统筹委员会体系",
        "org_name": "乌兰巴托首都禁毒预防协调分委会",
        "org_name_mn": "Улаанбаатар хотын мансууруулах бодисын эсрэг салбар хороо",
        "base_url": "https://ulaanbaatar.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["мансууруулах", "урьдчилан сэргийлэх"],
        "lang": "mn",
    },
    {
        "system_id": 1,
        "system_name": "国家级禁毒统筹委员会体系",
        "org_name": "全国毒品预防社会委员会",
        "org_name_mn": "Мансууруулах бодисоос урьдчилан сэргийлэх нийгмийн зөвлөл",
        "base_url": "https://www.mohs.mn",
        "seed_paths": ["/", "/news", "/info", "/announcement"],
        "keywords_extra": ["урьдчилан сэргийлэх", "нийгмийн"],
        "lang": "mn",
    },
    # ========== 2. 刑事缉毒执法体系 ==========
    {
        "system_id": 2,
        "system_name": "刑事缉毒执法体系",
        "org_name": "国家警察总局独立缉毒局",
        "org_name_mn": "Цагдаагийн ерөнхий газрын Мансууруулах бодистой тэмцэх газар",
        "base_url": "https://www.police.gov.mn",
        "seed_paths": ["/", "/news", "/info", "/press", "/announcement"],
        "keywords_extra": ["цагдаа", "баривчилгаа", "мөрдөн байцаалт", "seizure"],
        "lang": "mn",
    },
    {
        "system_id": 2,
        "system_name": "刑事缉毒执法体系",
        "org_name": "国家情报局 GIA 禁毒情报部门",
        "org_name_mn": "Тагнуулын ерөнхий газар",
        "base_url": "https://gia.gov.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["тагнуул", "мансууруулах", "intelligence"],
        "lang": "mn",
    },
    {
        "system_id": 2,
        "system_name": "刑事缉毒执法体系",
        "org_name": "总检察院毒品犯罪公诉局",
        "org_name_mn": "Улсын ерөнхий прокурорын газар",
        "base_url": "https://www.prosecutor.mn",
        "seed_paths": ["/", "/news", "/info", "/press"],
        "keywords_extra": ["прокурор", "мансууруулах", "гэмт хэрэг"],
        "lang": "mn",
    },
    {
        "system_id": 2,
        "system_name": "刑事缉毒执法体系",
        "org_name": "国家监狱管理局戒毒惩戒处",
        "org_name_mn": "Шүүхийн шийдвэр гүйцэтгэх ерөнхий газар",
        "base_url": "https://www.gs.gov.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["хорих", "нөхөн сэргээх", "мансууруулах"],
        "lang": "mn",
    },
    # ========== 3. 麻精药品与制毒原料行业监管体系 ==========
    {
        "system_id": 3,
        "system_name": "麻精药品与制毒原料行业监管体系",
        "org_name": "蒙古国卫生部麻精药品监管总局",
        "org_name_mn": "Эрүүл мэндийн яам",
        "base_url": "https://www.mohs.mn",
        "seed_paths": ["/", "/news", "/info", "/legal", "/announcement"],
        "keywords_extra": ["эм", "мансууруулах", "зохицуулалт", "precursor", "controlled"],
        "lang": "mn",
    },
    {
        "system_id": 3,
        "system_name": "麻精药品与制毒原料行业监管体系",
        "org_name": "环境与自然资源部毒品原植物监察处",
        "org_name_mn": "Байгаль орчин, аялал жуулчлалын яам",
        "base_url": "https://www.met.gov.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["ургамал", "опиум", "каннабис", "cannabis", "poppy"],
        "lang": "mn",
    },
    {
        "system_id": 3,
        "system_name": "麻精药品与制毒原料行业监管体系",
        "org_name": "国家药品医疗器械检验研究院（国家毒品实验室）",
        "org_name_mn": "Эм, эмнэлгийн хэрэгслийн хяналт, зохицуулалтын газар",
        "base_url": "https://www.mohs.mn",
        "seed_paths": ["/", "/news", "/lab", "/info"],
        "keywords_extra": ["лаборатори", "шинжилгээ", "narcotic lab"],
        "lang": "mn",
    },
    {
        "system_id": 3,
        "system_name": "麻精药品与制毒原料行业监管体系",
        "org_name": "药品医疗器械监管总局公开资讯",
        "org_name_mn": "Эм, эмнэлгийн хэрэгсэл",
        "base_url": "https://www.moh.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["мансууруулах эм", "зохицуулалт"],
        "lang": "mn",
    },
    # ========== 4. 边境海关缉毒查验体系 ==========
    {
        "system_id": 4,
        "system_name": "边境海关缉毒查验体系",
        "org_name": "海关边境管控总局全国禁毒查验支队",
        "org_name_mn": "Гаалийн ерөнхий газар",
        "base_url": "https://www.customs.gov.mn",
        "seed_paths": ["/", "/news", "/info", "/press", "/announcement"],
        "keywords_extra": ["гааль", "хил", "баривчилгаа", "customs", "border", "seizure"],
        "lang": "mn",
    },
    {
        "system_id": 4,
        "system_name": "边境海关缉毒查验体系",
        "org_name": "边防总局边境禁毒巡逻大队",
        "org_name_mn": "Хилийн цэргийн удирдах газар",
        "base_url": "https://bpo.gov.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["хил", "патруль", "мансууруулах", "border patrol"],
        "lang": "mn",
    },
    {
        "system_id": 4,
        "system_name": "边境海关缉毒查验体系",
        "org_name": "中蒙双边边境禁毒联络办公室（蒙方公开资讯）",
        "org_name_mn": "Хил орчмын хамтын ажиллагаа",
        "base_url": "https://www.mfa.gov.mn",
        "seed_paths": ["/", "/news", "/info", "/cooperation"],
        "keywords_extra": ["хил", "Хятад", "мансууруулах", "China", "border cooperation"],
        "lang": "mn",
    },
    {
        "system_id": 4,
        "system_name": "边境海关缉毒查验体系",
        "org_name": "移民局边境管控公开资讯",
        "org_name_mn": "Гадаадын иргэн, харьяатын газар",
        "base_url": "https://immigration.gov.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["хил", "мансууруулах", "trafficking"],
        "lang": "mn",
    },
    # ========== 5. 全国地方层级禁毒机构 ==========
    {
        "system_id": 5,
        "system_name": "全国地方层级禁毒机构",
        "org_name": "21省禁毒协调小组 / 省级警察局缉毒分队（警察总局地方动态）",
        "org_name_mn": "Аймгийн цагдаагийн газар",
        "base_url": "https://www.police.gov.mn",
        "seed_paths": ["/", "/news", "/aimag", "/local"],
        "keywords_extra": ["аймаг", "орон нутаг", "мансууруулах"],
        "lang": "mn",
    },
    {
        "system_id": 5,
        "system_name": "全国地方层级禁毒机构",
        "org_name": "乌兰巴托9大区社区禁毒工作站",
        "org_name_mn": "Улаанбаатар дүүргийн ажил",
        "base_url": "https://ulaanbaatar.mn",
        "seed_paths": ["/", "/news", "/district", "/info"],
        "keywords_extra": ["дүүрэг", "урьдчилан сэргийлэх", "мансууруулах"],
        "lang": "mn",
    },
    {
        "system_id": 5,
        "system_name": "全国地方层级禁毒机构",
        "org_name": "地方政府门户禁毒相关公开资讯",
        "org_name_mn": "Засгийн газрын мэдээ",
        "base_url": "https://www.zasag.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["мансууруулах", "гэмт хэрэгтэй тэмцэх"],
        "lang": "mn",
    },
    # ========== 6. 戒毒康复医疗机构体系 ==========
    {
        "system_id": 6,
        "system_name": "戒毒康复医疗机构体系",
        "org_name": "国家药物成瘾康复中心总院",
        "org_name_mn": "Харшил, мансуурлын эмчилгээний төв",
        "base_url": "https://www.mohs.mn",
        "seed_paths": ["/", "/news", "/health", "/rehab", "/info"],
        "keywords_extra": ["нөхөн сэргээх", "эмчилгээ", "донтсон", "rehabilitation", "addiction"],
        "lang": "mn",
    },
    {
        "system_id": 6,
        "system_name": "戒毒康复医疗机构体系",
        "org_name": "全国公立医院成瘾医学科公开资讯",
        "org_name_mn": "Эмнэлгийн мэдээ",
        "base_url": "https://www.moh.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["донтсон", "эмчилгээ", "мансууруулах"],
        "lang": "mn",
    },
    {
        "system_id": 6,
        "system_name": "戒毒康复医疗机构体系",
        "org_name": "官方备案戒毒社会组织公开动态",
        "org_name_mn": "Төрийн бус байгууллага",
        "base_url": "https://www.mohs.mn",
        "seed_paths": ["/", "/news", "/ngo", "/info"],
        "keywords_extra": ["ТББ", "урьдчилан сэргийлэх", "нөхөн сэргээх"],
        "lang": "mn",
    },
    # ========== 7. 国际禁毒协作机构 ==========
    {
        "system_id": 7,
        "system_name": "国际禁毒协作机构",
        "org_name": "UNODC 蒙古国办事处",
        "org_name_mn": "UNODC Mongolia",
        "base_url": "https://www.unodc.org",
        "seed_paths": [
            "/unodc/en/frontpage.html",
            "/easternasiaandpacific/mongolia.html",
            "/easternasiaandpacific/index.html",
            "/unodc/en/drug-trafficking/index.html",
        ],
        "keywords_extra": ["Mongolia", "UNODC", "drug", "trafficking", "precursor"],
        "lang": "en",
        "domain_allowlist": ["unodc.org", "www.unodc.org"],
    },
    {
        "system_id": 7,
        "system_name": "国际禁毒协作机构",
        "org_name": "蒙古国外交部国际禁毒合作司",
        "org_name_mn": "Гадаад харилцааны яам",
        "base_url": "https://www.mfa.gov.mn",
        "seed_paths": ["/", "/news", "/info", "/cooperation", "/press"],
        "keywords_extra": ["мансууруулах", "олон улсын", "хамтын ажиллагаа", "UNODC"],
        "lang": "mn",
    },
    {
        "system_id": 7,
        "system_name": "国际禁毒协作机构",
        "org_name": "蒙古国政府国际合作公开资讯",
        "org_name_mn": "Засгийн газрын олон улсын хамтын ажиллагаа",
        "base_url": "https://mongolia.gov.mn",
        "seed_paths": ["/", "/news", "/info"],
        "keywords_extra": ["мансууруулах", "олон улсын", "drug"],
        "lang": "mn",
    },
]

# 禁毒相关关键词（蒙/英/俄/中）——用于过滤无关政务新闻
DRUG_KEYWORDS = [
    # 中文
    "毒品", "禁毒", "缉毒", "麻精", "制毒", "戒毒", "成瘾", "贩毒", "走私毒品",
    "易制毒", "管制药品", "合成毒品", "冰毒", "海洛因", "大麻", "可卡因",
    "芬太尼", "跨境缉毒", "口岸查获", "专项行动", "毒情", "康复",
    # 蒙语（西里尔）
    "мансууруулах", "мансууруулах бодис", "хар тамхи", "донтсон",
    "урьдчилан сэргийлэх", "баривчилгаа", "хилээр нэвтрүүлэх",
    "синтетик", "опиум", "героин", "кокаин", "каннабис", "марихуан",
    "нөхөн сэргээх", "эмчилгээ", "зохицуулалт", "гэмт хэрэг",
    # 英语
    "drug", "narcotic", "trafficking", "seizure", "precursor", "controlled substance",
    "addiction", "rehabilitation", "opioid", "methamphetamine", "heroin", "cannabis",
    "cocaine", "fentanyl", "UNODC", "anti-drug", "interdiction", "border control",
    # 俄语
    "наркотик", "наркотиков", "контрабанда", "изъятие", "прекурсор",
    "наркомания", "реабилитация", "героин", "кокаин", "каннабис",
]

# 重大突发告警关键词
CRITICAL_KEYWORDS = [
    "专项行动", "跨境缉毒", "新法", "口岸严查", "合成毒品", "易制毒",
    "缉毒大案", "管制品", "大规模查获", "seizure", "operation",
    "баривчилгаа", "тусгай ажиллагаа", "хил", "UNODC",
]

# 允许爬取的官方域名白名单（严格限制）
ALLOWED_DOMAINS = [
    "police.gov.mn",
    "www.police.gov.mn",
    "ulaanbaatar.mn",
    "www.ulaanbaatar.mn",
    "mohs.mn",
    "www.mohs.mn",
    "moh.mn",
    "www.moh.mn",
    "gia.gov.mn",
    "www.gia.gov.mn",
    "prosecutor.mn",
    "www.prosecutor.mn",
    "gs.gov.mn",
    "www.gs.gov.mn",
    "met.gov.mn",
    "www.met.gov.mn",
    "customs.gov.mn",
    "www.customs.gov.mn",
    "bpo.gov.mn",
    "www.bpo.gov.mn",
    "mfa.gov.mn",
    "www.mfa.gov.mn",
    "immigration.gov.mn",
    "www.immigration.gov.mn",
    "zasag.mn",
    "www.zasag.mn",
    "mongolia.gov.mn",
    "www.mongolia.gov.mn",
    "unodc.org",
    "www.unodc.org",
    "legalinfo.mn",
    "www.legalinfo.mn",
]
